// Beverly's of Nashville — Master Strategy Data
// Design: "Gold Ledger" Art Deco Editorial

export const strategyMeta = {
  title: "Beverly's of Nashville",
  subtitle: "Master Growth & Marketing Strategy",
  year: "2026",
  preparedFor: "Teddy Chisom, Owner & Lead Stylist",
  location: "3304 Nolensville Pike, Nashville, TN 37211",
  phone: "615-497-4215",
  email: "teddy@beverlysofnashville.com",
  website: "beverlysofnashville.com",
};

export const revenuePillars = [
  {
    id: "salon",
    number: "01",
    title: "The Salon",
    focus: "Premium color corrections, silk presses, and luxury extensions",
    audience: "Nashville women (25–55) seeking high-end, reliable hair care",
    channel: "Instagram Reels, TikTok local SEO, and Google Business Profile",
    color: "gold",
    icon: "✂️",
  },
  {
    id: "wigs",
    number: "02",
    title: "Wig Boutique",
    focus: "Custom wigs for ALL women — fashion, protective styling, bridal, convenience, and medical",
    audience: "Every woman who wants to transform her look, protect her hair, or restore her confidence — 8 distinct segments from fashion enthusiasts to cancer patients",
    channel: "TikTok/Instagram for fashion segments, YouTube for education, Google SEO for medical, oncology partnerships for cranial prostheses",
    color: "gold",
    icon: "👑",
  },
  {
    id: "academy",
    number: "03",
    title: "The Academy",
    focus: "E-books, video courses, and in-person masterclasses",
    audience: "Aspiring cosmetologists and seasoned stylists seeking advanced skills",
    channel: "TikTok educational content, email marketing funnels, and industry networking",
    color: "gold",
    icon: "🎓",
  },
  {
    id: "content",
    number: "04",
    title: "Content Monetization",
    focus: "Ad revenue, brand sponsorships, and affiliate marketing",
    audience: "Global audience interested in hair transformations and education",
    channel: "YouTube Partner Program, TikTok Creator Rewards, and affiliate links",
    color: "gold",
    icon: "📱",
  },
];

export const wigMarketOverview = {
  globalMarketSize: "$3.65B (2022) → $5.10B (2030)",
  usWomenSpending: "$503 average annually on hair care (Black women)",
  wigSalesGrowth: "75% increase in wig sales (2020–2021), sustained trend",
  primaryDemographic: "Women aged 25–45 make up 80.4% of wig buyers",
  positioning: "Beverly's targets ALL women who want custom wigs — medical need is one important segment among many. The goal is to become Nashville's premier destination for every woman who wants to transform her look, protect her hair, or restore her confidence.",
};

export const wigAudienceSegments = [
  {
    id: "fashion",
    icon: "👑",
    segment: "Fashion & Style Enthusiasts",
    description: "Women who wear wigs as a fashion accessory — changing their look as often as they change their outfit. This is the largest and fastest-growing segment, driven by celebrity culture, social media, and the normalization of wigs as everyday style.",
    size: "Largest segment — millions of women nationwide",
    motivation: "Self-expression, versatility, trend participation, no chemical commitment",
    priceRange: "$300 – $1,200",
    marketingAngle: "'Your hair, your rules' — position custom wigs as the ultimate style accessory. Showcase bold colors, dramatic lengths, and trend-forward styles that would be impossible or damaging to achieve naturally.",
    contentIdeas: ["Wig of the week reveals", "'What I wore vs. what I actually wore' wig edition", "Color transformation without commitment", "Celebrity-inspired custom units"],
    platforms: ["Instagram Reels", "TikTok", "Pinterest"],
  },
  {
    id: "protective",
    icon: "🌿",
    segment: "Protective Styling Women",
    description: "Black women and women of color who wear wigs as a protective styling method to preserve the health of their natural hair. This is a deeply rooted cultural practice and a massive market — Black women spend 6x more on hair care than other demographics.",
    size: "$3.2B Black hair care market (2023); Black women spend $503/year on average",
    motivation: "Natural hair protection, growth retention, low manipulation, versatility",
    priceRange: "$250 – $900",
    marketingAngle: "Educate on the benefits of protective styling with quality wigs. Teddy's 30+ years of expertise with textured hair is a massive differentiator. Position Beverly's as the go-to for women who want to protect their crown while still looking flawless.",
    contentIdeas: ["'My natural hair grew 4 inches under this wig' reveals", "How to care for your natural hair while wearing a wig", "Wig install + protective style tutorial", "The real cost of NOT protecting your hair"],
    platforms: ["TikTok", "YouTube", "Instagram"],
  },
  {
    id: "convenience",
    icon: "⚡",
    segment: "Busy Professionals & Moms",
    description: "Women who wear wigs for pure convenience — eliminating the daily time spent on hair styling. A custom wig means waking up camera-ready in minutes. This segment is growing rapidly as women prioritize time efficiency.",
    size: "Massive — any professional woman or mother is a potential customer",
    motivation: "Time savings, consistency, low-maintenance beauty, always looking polished",
    priceRange: "$350 – $800",
    marketingAngle: "'Get ready in 5 minutes, look like you spent 2 hours.' Sell the time-freedom narrative. Show morning routine content demonstrating how a custom wig transforms the daily routine.",
    contentIdeas: ["'Get ready with me in 5 minutes' wig edition", "Working mom morning routine", "Before/after time-lapse of wig install", "'I haven't done my hair in 3 months and I look amazing'"],
    platforms: ["TikTok", "Instagram Reels", "Facebook"],
  },
  {
    id: "hairloss",
    icon: "🌸",
    segment: "Hormonal & Genetic Hair Loss",
    description: "Women experiencing hair thinning or loss due to hormonal changes — including menopause, postpartum shedding, thyroid disorders, PCOS, and androgenetic alopecia. This is an underserved segment that desperately needs compassionate, expert solutions.",
    size: "50M+ women in the US experience some form of hair loss",
    motivation: "Confidence restoration, natural appearance, discreet solutions, expert guidance",
    priceRange: "$600 – $2,000",
    marketingAngle: "Position Beverly's as a safe, judgment-free space for women navigating hair loss. Educational content that normalizes the conversation around hormonal hair loss builds deep trust and long-term client relationships.",
    contentIdeas: ["'Let's talk about postpartum hair loss' educational series", "Menopause and your hair — what to expect", "Thyroid hair loss solutions", "Alopecia awareness content"],
    platforms: ["YouTube", "Instagram", "Facebook Groups"],
  },
  {
    id: "medical",
    icon: "💜",
    segment: "Cancer Patients & Medical Hair Loss",
    description: "Women undergoing chemotherapy or other medical treatments that cause hair loss. This segment requires the highest level of compassion, expertise, and certification. Beverly's can bill insurance for cranial prostheses, making this both a community service and a high-revenue opportunity.",
    size: "Hundreds of thousands of women undergo chemo annually in the US",
    motivation: "Restoring normalcy, maintaining dignity, feeling like themselves during treatment",
    priceRange: "$1,500 – $3,500+ (often insurance-covered)",
    marketingAngle: "Lead with compassion, not commerce. Partner with Vanderbilt-Ingram Cancer Center, Tennessee Oncology, and Sarah Cannon Research Institute. Offer a private, dignified consultation experience. Insurance guidance is a service, not a sales pitch.",
    contentIdeas: ["'How to get your wig covered by insurance' guide", "What to expect at your first wig consultation", "Compassionate client stories (with consent)", "Nurse/oncologist partnership interviews"],
    platforms: ["YouTube", "Facebook", "Google Search (SEO)"],
  },
  {
    id: "alopecia",
    icon: "🦋",
    segment: "Alopecia Community",
    description: "Women living with alopecia areata, totalis, or universalis — a community that is deeply connected, vocal on social media, and actively seeking expert wig specialists. This community shares recommendations widely and is extremely loyal to trusted providers.",
    size: "6.8 million Americans have alopecia areata; global community is massive on social media",
    motivation: "Natural-looking coverage, scalp comfort, community connection, expert fitting",
    priceRange: "$800 – $2,500",
    marketingAngle: "Become a visible advocate in the alopecia community. Use hashtags like #alopecia, #alopeciawarrior, and #baldandbeautiful. Partner with the National Alopecia Areata Foundation (NAAF). Alopecia community members are extremely loyal and share recommendations widely.",
    contentIdeas: ["Alopecia awareness content", "'My alopecia journey' client stories", "Wig fitting for sensitive scalps tutorial", "NAAF partnership events"],
    platforms: ["TikTok", "Instagram", "YouTube"],
  },
  {
    id: "bridal",
    icon: "💍",
    segment: "Bridal & Special Occasion",
    description: "Brides and women attending major life events who want flawless, guaranteed hair for their most important moments. A custom wig eliminates the risk of a bad hair day on a wedding day. This is a premium, high-ticket segment with strong referral potential.",
    size: "2M+ weddings annually in the US; every bride is a potential client",
    motivation: "Perfection on their special day, guaranteed look, no bad hair day risk",
    priceRange: "$600 – $1,500",
    marketingAngle: "Market to brides, bridesmaids, and mother-of-the-bride. Partner with Nashville wedding planners, bridal boutiques, and event venues. Offer bridal wig packages with trial fittings.",
    contentIdeas: ["Bridal wig reveal content", "'I wore a wig on my wedding day and here's why' stories", "Wedding hair transformation videos", "Bridal party wig styling"],
    platforms: ["Instagram", "Pinterest", "TikTok"],
  },
  {
    id: "experimental",
    icon: "🎨",
    segment: "Color & Style Experimenters",
    description: "Women who want to try bold colors, dramatic cuts, or fantasy styles without any chemical commitment or damage to their natural hair. This segment is highly active on social media and creates viral content naturally.",
    size: "Rapidly growing with social media influence; Gen Z and Millennial-driven",
    motivation: "Risk-free experimentation, trend participation, creative self-expression",
    priceRange: "$250 – $700",
    marketingAngle: "Showcase Teddy's color expertise through bold, eye-catching wig transformations. Blue, red, platinum, ombre — content that stops the scroll. Position Beverly's as the place where women can be bold without consequences.",
    contentIdeas: ["Bold color wig reveals", "'I went platinum blonde for a day' content", "Fantasy color wig builds", "Color trend reaction content"],
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
  },
];

export const wigTiers = [
  {
    tier: "Ready-to-Wear Custom",
    price: "$250 – $600",
    customer: "Fashion buyers, protective styling clients, and style experimenters seeking immediate transformation",
    marketing: "Instagram Reels and TikTok showcasing quick reveals, bold colors, and styling versatility. 'Your wig, ready when you are.'",
  },
  {
    tier: "Premium Fully Custom",
    price: "$700 – $1,500",
    customer: "Bridal clients, busy professionals, alopecia clients, and luxury fashion buyers who want a unit built specifically for their head shape, lifestyle, and aesthetic",
    marketing: "YouTube process videos showing the full construction journey. Behind-the-scenes content of Teddy hand-building a unit from scratch. 'This wig was made for you and only you.'",
  },
  {
    tier: "Cranial Prosthesis (Medical)",
    price: "$1,500 – $3,500+ (insurance-eligible)",
    customer: "Cancer patients, severe alopecia clients, and women with medically-induced hair loss who need a compassionate, certified specialist and insurance guidance",
    marketing: "Oncology center partnerships, compassionate SEO content, support group networking, and referral programs with medical professionals. Insurance guidance is the key differentiator.",
  },
];

export const wigMarketingChannels = [
  {
    channel: "TikTok & Instagram Reels",
    segments: ["Fashion", "Protective Styling", "Convenience", "Color Experimenters"],
    strategy: "High-energy transformation content, bold color reveals, quick install tutorials, trending audio. Focus on the 'wow factor' and scroll-stopping visuals.",
    budget: "Organic first, then $20–50/day Spark Ads on top performers",
  },
  {
    channel: "YouTube Long-Form",
    segments: ["Protective Styling", "Hormonal Hair Loss", "Medical", "Bridal"],
    strategy: "Educational deep-dives, wig construction process videos, client journey documentaries, insurance guides. Builds trust and ranks in Google search.",
    budget: "$0 (organic) — monetizes through YouTube Partner Program once eligible",
  },
  {
    channel: "Google SEO & Ads",
    segments: ["Medical", "Alopecia", "Hormonal Hair Loss"],
    strategy: "Target high-intent search terms: 'wigs for cancer patients Nashville,' 'alopecia wig specialist Nashville,' 'insurance covered wigs TN.' These buyers are actively searching for solutions.",
    budget: "$300–500/month for Google Ads; SEO is organic long-term investment",
  },
  {
    channel: "Oncology & Medical Partnerships",
    segments: ["Medical", "Alopecia"],
    strategy: "Place brochures at Vanderbilt-Ingram, Tennessee Oncology, and Sarah Cannon. Offer free consultation days at facilities. Build referral relationships with oncology nurses and social workers.",
    budget: "Low cost — primarily time investment and printed materials",
  },
  {
    channel: "Pinterest & Bridal Networks",
    segments: ["Bridal", "Fashion", "Color Experimenters"],
    strategy: "Create boards for bridal wig inspiration, color transformation galleries, and style lookbooks. Partner with Nashville wedding planners and bridal boutiques for cross-referrals.",
    budget: "$0 organic + optional promoted pins ($10–20/day)",
  },
  {
    channel: "Facebook Groups & Community",
    segments: ["Hormonal Hair Loss", "Alopecia", "Medical", "Protective Styling"],
    strategy: "Join and contribute value to Nashville women's groups, alopecia support communities, and cancer patient groups. Never sell directly — provide expertise and let the referrals come naturally.",
    budget: "$0 — relationship-based marketing",
  },
];

export const academyLadder = [
  {
    step: 1,
    title: "The Lead Magnet",
    price: "Free",
    description: "A high-value PDF — \"The Master Colorist's Cheat Sheet\" — offered in exchange for an email address. This builds the marketing database.",
    tag: "Lead Generation",
  },
  {
    step: 2,
    title: "Entry-Level E-Books",
    price: "$29 – $79",
    description: "Highly specific, actionable guides. Examples include a \"Hair Color Theory & Formulation Guide\" or a \"Wig Construction 101\" manual.",
    tag: "Passive Income",
  },
  {
    step: 3,
    title: "Mid-Tier Video Courses",
    price: "$197 – $497",
    description: "Comprehensive, multi-module video training hosted on a platform like Teachable. A \"Custom Wig Building Masterclass\" showing Teddy's exact process.",
    tag: "Core Revenue",
  },
  {
    step: 4,
    title: "In-Person Masterclasses",
    price: "$997 – $1,500",
    description: "Exclusive, two-day weekend workshops hosted at the Nashville salon, limited to 8–10 students for hands-on instruction.",
    tag: "High-Ticket",
  },
  {
    step: 5,
    title: "Elite Private Mentorship",
    price: "$3,000+",
    description: "A three-month, one-on-one virtual coaching program for salon owners looking to scale their own businesses.",
    tag: "Premium",
  },
];

export const viral50 = {
  authority: [
    { id: 1, title: "The 3-Second Rule", desc: "Why your box dye is destroying your hair (stitch a viral hair fail)" },
    { id: 2, title: "Color Mixing ASMR", desc: "A highly satisfying, silent video of mixing complex color formulas at the bowl" },
    { id: 3, title: "The 'Why' Behind the Price", desc: "Breaking down the cost of a $1,200 custom wig versus a $90 synthetic wig" },
    { id: 4, title: "Debunking Natural Hair Myths", desc: "Addressing common misconceptions about silk presses and heat damage" },
    { id: 5, title: "The Perfect Consultation", desc: "Role-playing how a master stylist conducts a first-time client consultation" },
    { id: 6, title: "Tool Talk", desc: "Teddy's top 5 essential tools after 30 years in the business (with affiliate links)" },
    { id: 7, title: "Product Breakdown", desc: "Why professional color lines outperform drugstore brands" },
    { id: 8, title: "The Science of Gray Coverage", desc: "Explaining the underlying pigment of stubborn gray hair" },
    { id: 9, title: "Wig Ventilation 101", desc: "A close-up, sped-up timelapse of hand-tying hair into a lace cap" },
    { id: 10, title: "The 'Save My Hair' Series", desc: "Reviewing follower-submitted hair disaster photos and explaining how Teddy would fix them" },
  ],
  emotional: [
    { id: 11, title: "The Reveal", desc: "A cancer patient seeing herself with hair for the first time in months (with strict consent)" },
    { id: 12, title: "The Insurance Guide", desc: "A 60-second breakdown of how to get a cranial prosthesis covered by insurance" },
    { id: 13, title: "Wig Care During Chemo", desc: "Essential tips for maintaining a wig and a sensitive scalp during treatment" },
    { id: 14, title: "The 'Beautiful You' Event", desc: "A montage of the quarterly free wig styling day for oncology patients" },
    { id: 15, title: "A Nurse's Perspective", desc: "An interview clip with a local oncology nurse discussing the psychological impact of hair loss" },
    { id: 16, title: "The Measurement Process", desc: "Showing the delicate, respectful process of measuring a client for a medical wig" },
    { id: 17, title: "Mother-Daughter Moments", desc: "Capturing the emotional support system during a medical wig fitting" },
    { id: 18, title: "The 'Why I Do This' Story", desc: "Teddy speaking directly to the camera about why he pursued cranial prosthesis certification" },
    { id: 19, title: "Styling a Medical Wig", desc: "Demonstrating how to safely heat-style a human hair cranial prosthesis" },
    { id: 20, title: "Client Testimonial", desc: "A sit-down, documentary-style clip of a survivor discussing her journey with Beverly's" },
  ],
  transformations: [
    { id: 21, title: "The 8-Hour Color Correction", desc: "A sped-up timelapse of a massive transformation, set to trending audio" },
    { id: 22, title: "The Perfect Silk Press", desc: "The satisfying 'before and after' of natural hair to glass-like straight hair" },
    { id: 23, title: "The 'Trust the Process' Video", desc: "Showing the scary middle stages of a color correction before the beautiful final result" },
    { id: 24, title: "Day in the Life", desc: "A fast-paced vlog of a 10-hour Saturday at Beverly's of Nashville" },
    { id: 25, title: "The Legacy Story", desc: "A tribute video to Beverly Epps and the 30-year history of the salon on Nolensville Pike" },
    { id: 26, title: "Client Reactions", desc: "A compilation of clients seeing their final look in the mirror for the first time" },
    { id: 27, title: "The 'Oops' Moment", desc: "A relatable, humorous video about a minor salon mishap and recovering gracefully" },
    { id: 28, title: "Stylist vs. Stylist", desc: "A friendly, fast-paced styling competition between Teddy and another Beverly's stylist" },
    { id: 29, title: "The 'I've Been Doing Hair Since...' Trend", desc: "Participating in the viral trend highlighting Teddy's longevity in the industry" },
    { id: 30, title: "The Salon Tour", desc: "A cinematic walkthrough of the luxury space, highlighting the styling stations and private wig room" },
  ],
  trends: [
    { id: 31, title: "POV: Finally Booked", desc: "You finally booked with the master stylist you've been following for months" },
    { id: 32, title: "What I Asked For vs. What I Got", desc: "Showing a Pinterest reference photo followed by Teddy's flawless execution" },
    { id: 33, title: "Client Red Flags", desc: "A humorous take on things clients do that drive stylists crazy" },
    { id: 34, title: "The 'My Stylist Told Me To...' Audio", desc: "Using trending audio to reinforce good hair care habits" },
    { id: 35, title: "The 'Quiet Luxury' Trend", desc: "Showcasing the high-end, understated elegance of a Beverly's custom wig" },
    { id: 36, title: "The 'Girl Math' Trend", desc: "Explaining why investing in a $1,000 custom wig that lasts 3 years is actually saving money" },
    { id: 37, title: "The 'Roman Empire' Trend", desc: "What Teddy thinks about constantly (e.g., perfect color formulation)" },
    { id: 38, title: "The 'Get Ready With Me' (GRWM)", desc: "Teddy getting ready for a fully booked Saturday at the salon" },
    { id: 39, title: "The 'Unpopular Opinion'", desc: "A controversial but expert take on a popular hair trend or product" },
    { id: 40, title: "The 'I'm a Master Stylist, Of Course I...' Trend", desc: "Highlighting the unique quirks of being an industry veteran" },
  ],
  sales: [
    { id: 41, title: "The E-Book Teaser", desc: "A quick tip from the 'Hair Color Theory Guide' with a call-to-action to download the full book" },
    { id: 42, title: "The Masterclass Sneak Peek", desc: "High-energy B-roll from an in-person Academy event, showing students learning hands-on" },
    { id: 43, title: "The 'Link in Bio' Tour", desc: "Showing followers exactly where to click to book an appointment or buy a wig" },
    { id: 44, title: "The 'Sold Out' Flex", desc: "Celebrating when a masterclass or a specific wig collection sells out, creating scarcity and FOMO" },
    { id: 45, title: "The Mentorship Success Story", desc: "An interview with a stylist who doubled their income after taking Teddy's business course" },
    { id: 46, title: "The 'Behind the Course' Video", desc: "Showing the professional filming setup for The Academy's digital products" },
    { id: 47, title: "The 'Ask Me Anything' Promo", desc: "Promoting the upcoming live ticketed webinar and answering one free question" },
    { id: 48, title: "The 'Flash Sale' Announcement", desc: "A 24-hour discount on a specific digital product or ready-to-wear wig" },
    { id: 49, title: "The 'Join the Waitlist' Teaser", desc: "Building anticipation for the next enrollment period of the elite mentorship program" },
    { id: 50, title: "The 'Invest in Yourself' Monologue", desc: "A direct, motivational address to aspiring stylists about the importance of continuing education" },
  ],
};

export const events = [
  {
    name: "\"Beautiful You\" Wig Day",
    frequency: "Quarterly",
    goal: "Community impact & oncology partnerships",
    revenue: "Indirect (long-term referrals and insurance billing)",
    content: "Emotional transformations, nurse interviews, local news coverage",
  },
  {
    name: "Teddy's Masterclass",
    frequency: "Bi-Annually",
    goal: "High-ticket education revenue",
    revenue: "$8,000 – $15,000 per event (8–10 seats at $1,000+)",
    content: "Educational B-roll, student testimonials, promotional material for digital courses",
  },
  {
    name: "The Legacy Gala",
    frequency: "Annually",
    goal: "VIP client retention & brand prestige",
    revenue: "High (ticket sales, VIP wig pre-orders, luxury product bundles)",
    content: "Glamorous event photography, red carpet interviews, brand legacy videos",
  },
  {
    name: "Pop-Up Wig Boutique",
    frequency: "Quarterly",
    goal: "Direct sales & market expansion",
    revenue: "$5,000 – $10,000 per event (ready-to-wear sales)",
    content: "Live try-on Reels, customer reaction videos, 'day in the life' vlogs",
  },
  {
    name: "Live 'Ask Teddy' Webinar",
    frequency: "Monthly",
    goal: "Lead generation & digital product sales",
    revenue: "$1,500 – $5,000 (ticket sales + backend course upsells)",
    content: "Long-form YouTube content, short-form Q&A clips for TikTok/Reels",
  },
];

export const revenueDistribution = [
  { stream: "Physical Salon Services", percent: 35, scalability: "Low", margin: "Medium" },
  { stream: "Custom Wigs & Cranial Prostheses", percent: 30, scalability: "Medium", margin: "High" },
  { stream: "The Academy (Digital Products)", percent: 20, scalability: "Infinite", margin: "Ultra-High (95%+)" },
  { stream: "In-Person Education & Mentorship", percent: 10, scalability: "Low", margin: "Ultra-High" },
  { stream: "Content Monetization & Affiliates", percent: 5, scalability: "Infinite", margin: "Ultra-High (100%)" },
];

export const roadmapPhases = [
  {
    phase: "Phase 1",
    title: "Foundation & Infrastructure",
    days: "Days 1–30",
    items: [
      "Secure beverlysofnashville.com and set up professional email",
      "Create optimized Instagram and TikTok business accounts",
      "Acquire filming equipment (ring light, tripod, wireless mic)",
      "Design and launch the free PDF lead magnet",
      "Ensure Cranial Prosthesis Certification is current",
      "Install Google Analytics 4 and Meta Pixel on the website",
      "Set up Linktree and integrate booking widget (Booksy/Vagaro)",
    ],
  },
  {
    phase: "Phase 2",
    title: "Product Launch & Audience Growth",
    days: "Days 31–60",
    items: [
      "Add The Academy hub and blog to the website",
      "Publish first 4 SEO-optimized articles targeting salon and wig keywords",
      "Write, design, and launch the first paid e-book via Gumroad or Stripe",
      "Host the first Instagram Live Q&A session",
      "Run a strategic giveaway (e.g., a free wig consultation)",
      "Initiate contact with three major Nashville oncology centers",
      "Add dedicated Insurance/Medical Wig page to the website",
    ],
  },
  {
    phase: "Phase 3",
    title: "Scaling & Advanced Monetization",
    days: "Days 61–90",
    items: [
      "Launch the second digital product (\"Wig Construction 101\" e-book)",
      "Host the first ticketed live webinar",
      "Begin filming video modules for the \"Master Color Formulation\" course",
      "Establish the YouTube channel and post first long-form video",
      "Deploy Google Ads targeting medical wig keywords ($300–$500/month)",
      "Run TikTok Spark Ads on top-performing organic videos",
      "Host the first \"Beautiful You\" free wig consultation day for cancer patients",
    ],
  },
];

export const matrixScenarios = [
  {
    label: "Scenario A",
    title: "The Salon Client",
    steps: [
      "Client books a premium color service ($300)",
      "Teddy recommends a professional shampoo → affiliate commission ($15)",
      "Transformation filmed → posted to YouTube Shorts and TikTok → ad revenue ($5)",
      "Content attracts two new local clients ($600)",
    ],
    total: "$920",
    multiplier: "3.1×",
  },
  {
    label: "Scenario B",
    title: "The Medical Wig Client",
    steps: [
      "Oncology nurse refers a patient",
      "Teddy provides a custom cranial prosthesis, billed to insurance ($2,500)",
      "Client subscribes to quarterly wig maintenance plan ($600/year)",
      "Story featured on the blog → improves SEO → drives three more consultations",
    ],
    total: "$3,100+",
    multiplier: "5×+",
  },
  {
    label: "Scenario C",
    title: "The Aspiring Stylist",
    steps: [
      "Cosmetology student discovers Teddy on TikTok",
      "Downloads free PDF → enters email funnel",
      "Purchases \"Color Theory E-Book\" ($49)",
      "Enrolls in \"Master Color Formulation\" video course ($297)",
      "Flies to Nashville for the in-person Masterclass ($1,200)",
    ],
    total: "$1,546",
    multiplier: "∞ (digital)",
  },
];

export const immediateActions = [
  {
    priority: 1,
    action: "Secure the Domain & Update the Website",
    detail: "Purchase beverlysofnashville.com immediately. Remove all placeholder text, integrate a booking system, and create the dedicated 'Medical Wigs' and 'The Academy' landing pages.",
  },
  {
    priority: 2,
    action: "Verify Medical Certification",
    detail: "Confirm Teddy's Cranial Prosthesis Certification status. If lapsed or not yet acquired, enroll in a certification course immediately — this is the key to unlocking the high-margin insurance reimbursement market.",
  },
  {
    priority: 3,
    action: "Launch the Content Engine",
    detail: "Commit to the 90-day content challenge. Film 5 videos per week (a mix of transformations, education, and process videos) and post daily across TikTok, Instagram Reels, and YouTube Shorts.",
  },
  {
    priority: 4,
    action: "Develop the First Digital Asset",
    detail: "Write and design the 'Hair Color Theory Guide' e-book. This serves as the proof-of-concept for The Academy and begins generating passive revenue to fund further marketing efforts.",
  },
  {
    priority: 5,
    action: "Initiate Oncology Outreach",
    detail: "Draft a compassionate, professional introductory letter and information packet to send to the patient care coordinators at Vanderbilt-Ingram Cancer Center and Tennessee Oncology.",
  },
];
